### ISSUE TITLE
Frage: Wie kommt man zum Schlüsselcode der Netz Noe

### ISSUE THREAD

**Issue by schup** [langi0815/Netz_NOE_SmartMeter_P1_Reader#1]
Hallo,

vielleicht kann ja hier jemand helfen.

Ich bin den Anweisungen des PDF Dokuments gefolgt und habe die e-mail an smartmeter@netz-noe.at geschickt.
Ausser einer automatisierten e-mail "Ihre Nachricht ist bei uns angekommen und befindet sich in guten Händen. " hat sich nichts getan. Das ist jetzt 2 1/2 Monat her.
Die lokalen Netz NOe Mitarbeiter haben keine Ahnung. 

https://www.netz-noe.at/Netz-Niederosterreich/Smart-Meter/Informationen.aspx -> 
https://www.netz-noe.at/Download-(1)/Smart-Meter/218_9_SmartMeter_Kundenschnittstelle_lektoriert_14.aspx

Den verschlüsselten Datensatz kann ich auslesen - fange halt nicht viel damit an.

**Comment by langi0815** [comment]
Hi,
Bei mir hat das auch relativ lange gedauert. Ich hab dann mal direkt bei der Smart Meter Hotline angerufen ([https://www.netz-noe.at/Kontakt.aspx](https://www.netz-noe.at/Kontakt.aspx) - 02236-201-2070).  Die haben dann gesehen, dass ich den Key angefordert habe und konnten mir auch Auskunft zum Status geben.

lg

**Comment by schup** [comment]
Vielen Dank,
Laut hotline wissen die von nichts und brauchen zusaetzlich noch Telefon nummer und eine Ausweiskopie. 

Die ganzen Daten nochmal an info@netz-noe.at geschickt da der Support anscheinend keinen Zugriff auf die smartmeter@netz-noe.at hat. 

Mal schauen :-)

**Comment by schup** [comment]
Letzter Status: die Lange ist die Gleich

Noch ein 2. Mal mit der Smart Meter Hotline telefoniert (vor 5 Tagen) und der hat gemeint Ausweis und Telefon ist Blödsinn und im System war noch immer nichts.

Werde in ein paar Tagen wieder mal nachfragen.

Wieso einfach wenn es auch kompliziert sein kann :-(

**Comment by schup** [comment]
Endlich, Schlüssel kam per e-mail in verschlüsselter zip Datei.
Passwort für die zip Datei als SMS. 

Handy Nummer wird also doch gebraucht. 

Ich habe ein paar richtige Werte auslesen können aber die meisten Datensätze liefern Fehler.
Bei mir ist ein Kaifa MA309 verbaut.

... debugging ...

**Comment by langi0815** [comment]
Hi,
Ich bin mir nicht sicher, ob dieses Skript mit einem Kaifa MA309 funktioniert, aber hier gibt's ein Projekt zum Kaifa MA309:

[https://www.michaelreitbauer.at/kaifa-ma309-auslesen-smart-meter-evn/](https://www.michaelreitbauer.at/kaifa-ma309-auslesen-smart-meter-evn/)

lg

**Comment by schup** [comment]
Vielen Dank für den Link.
Mit dem Programm funktioniert es. 

War nicht so einfach zum Laufen zu bekommen wie Deine Lösung aber mit ein wenig trial&error bekomme ich jetzt Daten.

![image](https://user-images.githubusercontent.com/112154/158806155-5bebb937-8fc2-4125-a9a5-5e364d4a367b.png)
